
default: &default
  adapter: postgresql
  encoding: utf8
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: pguser
  password: password

development:
  <<: *default
  database: clevertodo_development


test:
  <<: *default
  database: clevertodo_test


production:
  <<: *default
  database: clevertodo_production
  username: clevertodo
  password: <%= ENV['CLEVERTODO_DATABASE_PASSWORD'] %>
  min_messages: warning
  timeout: 5000
